### ISSUE TITLE
Polymorphism is not validated

### ISSUE THREAD

**Issue by pieterbos** [openEHR/specifications-ITS-JSON#8]
The JSON schema does not validate any polymorphism. It contains for example in CLUSTER.json, for the items property:

```json
 "items": {
            "description": "Ordered list of items - `CLUSTER` or `ELEMENT` objects - under this `CLUSTER`. ",
            "type": "array",
            "items": {
                "$ref": "all.json#/definitions/ITEM"                
            },
            "minItems": 1
        }
```

Instead, it could be:

```json
 "items": {
            "description": "Ordered list of items - `CLUSTER` or `ELEMENT` objects - under this `CLUSTER`. ",
            "type": "array",
            "items": {
                "anyOf": [
                    {"$ref": "all.json#/definitions/CLUSTER"},
                    {"$ref": "all.json#/definitions/ELEMENT"}
                ]
            },
            "minItems": 1
        }
```

But then of course one should add the _type property on CLUSTER and ELEMENT as an optional property with a fixed value, to distinguish between the two.

I think this would make validation much more useful than it currently is, since now you can validate deeper layers of clusters and item structures - currently it stops at one level deep because there is no items property in ITEM.

**Comment by sebastian-iancu** [comment]
Polymorphism is still an aspect which I don't have a perfect solution for.
To my knowledge, using `“additionalProperties”: false` is not a solution as it prevents use 'extended' types, so I deliberately avoided `additionalProperties` in the schema (default behavior is that additional options are always allowed). The idea is however to require the `_type` property on children **only** in such situation as described above (i.e. we don't want to have that property all the time).
But your suggestion to use `anyOf` instead of `$ref` might be a valid option - I will need to do some experiments with it.
Why do you need to change to `"minItems": 0` ?

**Comment by pieterbos** [comment]
Yes, the polymorphism is tricky - combining the check for _type only when required and at the same time checking polymorphism with anyOf is not straightforward in json schema. I guess it's possible if you include some types twice - once with the _type and once without.

I would say that the polymorphism checks might be more important than checking for _type. If we supply an observation for example, any content in data or state will currently not be validated at all because of the missing items property in ITEM_STRUCTURE, so is considered an additonal property.

additionalProperties: false might not be a good thing to always include - I transform the json schema to add it for just one test to see if I do not serialize extra fields. May not be a good addition to the standard schemas :)

The change to minItems: 0 was a leftover from some of my tests, that should not be there, my apologies.

**Comment by pieterbos** [comment]
Oh you can actually do:

```json
"anyOf": [
    {
        "allOf": [
            {"$ref": "#/definitions/CLUSTER"},
            {"properties": {  "_type": {"const": "CLUSTER"}  } }
        ]
   },
    {
        "allOf": [
            {"$ref": "#/definitions/ELEMENT"},
            {"properties": {  "_type": {"const": "ELEMENT"}  } }
        ]
   }

]
```

Which means that only in these cases of ELEMENT and CLUSTER it should have the type property.

**Comment by pieterbos** [comment]
And as a quick test I created from the BMM:

https://gist.github.com/pieterbos/3b9a191ea09ace513ad3d3081116b7ea

That seems to work (schema is not complete!). Of course this only does OBSERVATION due to line number 2. You could put many types there, but that makes things very slow and very very hard to debug in case they go wrong :)

**Comment by pieterbos** [comment]
Updated so it can handle multiple root types without problems (but only if on the root has a _type property, does not validate otherwise):

https://gist.github.com/pieterbos/37bcee35e7aed4d2f0a431b17acf7bce

Also changed the `anyof` for polymorphic type to if/then constructions. This makes the output readable, otherwise you would get a *__lot__* of validation messages on every errorm since the validator has to report every type possible on every failure, instead of just the single type detected by the `"if": {"_type": {"const":"TYPENAME"}}` construction. Thousands of messages back to just a few.

Also added EVENT.data. Note that for other cases of generics, still problems.
